version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: al-folio-local-docker # amirpourmand/al-folio
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
